export const ADD_PRODUCT_TO_CART = "ADD_PRODUCT_TO_CART"

export const REMOVE_PRODUCT_TO_CART = "REMOVE_PRODUCT_TO_CART"

export const CHANGE_QTE_PRODUCT_IN_CART = "CHANGE_QTE_PRODUCT_IN_CART"

export const EMPTY_CART = "EMPTY_CART"
