// Products List Filters
export const SET_CATEGORIE_FILTER_VALUE = "SET_CATEGORIE_FILTER_VALUE"
export const SET_BRAND_FILTER_VALUE = "SET_BRAND_FILTER_VALUE"
export const SET_PRICE_FILTER_VALUE = "SET_PRICE_FILTER_VALUE"
export const SET_SEARCH_FILTER_VALUE = "SET_SEARCH_FILTER_VALUE"

// Orders History Filters
export const SET_ORDER_NUMBER_FILTER_VALUE = "SET_ORDER_NUMBER_FILTER_VALUE"
export const SET_ORDER_STATUS_FILTER_VALUE = "SET_ORDER_STATUS_FILTER_VALUE"
export const SET_ORDER_DATE_FILTER_VALUE = "SET_ORDER_DATE_FILTER_VALUE"
export const SET_ORDER_AMOUNT_FILTER_VALUE = "SET_ORDER_AMOUNT_FILTER_VALUE"





export const REMOVE_FILTERS_VALUES = "REMOVE_FILTERS_VALUES" 